development:
  adapter: postgresql
  database: forecash_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: forecash_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: forecash
  pool: 5
  timeout: 5000
